### ISSUE TITLE
Error after running "npm run dev" cmd

### ISSUE THREAD

**Issue by korem7** [574BandOfBrothers/memoriae#30]
When we run "npm run dev" in /memoriae/memoriae-api directory, we get following error:

Error: Cannot find module './environments/development.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/korem7/Desktop/memoriae/memoriae-api/src/config/environment.js:1:86)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! memoriae-api@0.0.1 start: `node src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the memoriae-api@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/korem7/.npm/_logs/2017-10-28T13_29_07_560Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ardaogulcan** [comment]
You should copy src/config/environments/environmets.json.example to same directory as development.json and you should fill variables with yoru environment variables
