### ISSUE TITLE
Can't determine id of Simulator app

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#42]
While starting IOS simulator of Expo I get the following error.

```
16:57:35: Starting iOS...
Can't determine id of Simulator app; the Simulator is most likely not installed on this machine { Error: spawn osascript ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn osascript',
  path: 'osascript',
  spawnargs: [ '-e', 'id of app "Simulator"' ],
  cmd: 'osascript -e id of app "Simulator"' }
Unable to verify Xcode and Simulator installation.

 › Press a to open Android device or emulator, or i to open iOS emulator.
 › Press q to display QR code.
 › Press r to restart packager, or R to restart packager and clear cache.
 › Press d to toggle development mode. (current mode: development)

16:58:47: Warning: You are using npm version 5.5.1. There may be bugs in this version, use it at your own risk. We recommend version 4.6.1.


```

**Comment by fatiharaci** [comment]
Installing simulator solves this issue.
