### ISSUE TITLE
Docker Install Error

### ISSUE THREAD

**Issue by fatiharaci** [574BandOfBrothers/memoriae#77]
After installing docker with following commands:
```
docker-compose build
docker-compose up
```
following error is taken

Docker takes following error:
`ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?`

**Comment by fatiharaci** [comment]
It seems post install steps are missing:

https://docs.docker.com/engine/installation/linux/linux-postinstall/#manage-docker-as-a-non-root-user

```
sudo groupadd docker
sudo usermod -aG docker $USER
sudo chown "$USER":"$USER" /home/"$USER"/.docker -R

```
actually first 2 helped me build docker

**Comment by fatiharaci** [comment]
however this problem still exist:

```
api_1    | Error: Cannot find module './environments/development.json'
api_1    |     at Function.Module._resolveFilename (module.js:542:15)
api_1    |     at Function.Module._load (module.js:472:25)
api_1    |     at Module.require (module.js:585:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at Object.<anonymous> (/app/src/config/environment.js:3:24)
api_1    |     at Module._compile (module.js:641:30)
api_1    |     at Object.Module._extensions..js (module.js:652:10)
api_1    |     at Module.load (module.js:560:32)
api_1    |     at tryModuleLoad (module.js:503:12)
api_1    |     at Function.Module._load (module.js:495:3)
api_1    |     at Module.require (module.js:585:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at Object.<anonymous> (/app/src/index.js:8:16)
api_1    |     at Module._compile (module.js:641:30)
api_1    |     at Object.Module._extensions..js (module.js:652:10)
api_1    |     at Module.load (module.js:560:32)
api_1    |     at tryModuleLoad (module.js:503:12)
api_1    |     at Function.Module._load (module.js:495:3)
api_1    |     at Module.require (module.js:585:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at Object.<anonymous> (/app/specs/index.spec.js:3:13)
api_1    |     at Module._compile (module.js:641:30)
api_1    |     at Object.Module._extensions..js (module.js:652:10)
api_1    |     at Module.load (module.js:560:32)
api_1    |     at tryModuleLoad (module.js:503:12)
api_1    |     at Function.Module._load (module.js:495:3)
api_1    |     at Module.require (module.js:585:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at /app/node_modules/mocha/lib/mocha.js:230:27
api_1    |     at Array.forEach (<anonymous>)
api_1    |     at Mocha.loadFiles (/app/node_modules/mocha/lib/mocha.js:227:14)
api_1    |     at Mocha.run (/app/node_modules/mocha/lib/mocha.js:495:10)
api_1    |     at Object.<anonymous> (/app/node_modules/mocha/bin/_mocha:460:18)
api_1    |     at Module._compile (module.js:641:30)
api_1    |     at Object.Module._extensions..js (module.js:652:10)
api_1    |     at Module.load (module.js:560:32)
api_1    |     at tryModuleLoad (module.js:503:12)
api_1    |     at Function.Module._load (module.js:495:3)
api_1    |     at Function.Module.runMain (module.js:682:10)
api_1    |     at startup (bootstrap_node.js:191:16)
api_1    |     at bootstrap_node.js:613:3
api_1    | npm ERR! code ELIFECYCLE
api_1    | npm ERR! errno 1
api_1    | npm ERR! memoriae-api@0.0.1 test:docker: `NODE_ENV=test_docker mocha specs --recursive`
api_1    | npm ERR! Exit status 1
api_1    | npm ERR! 
api_1    | npm ERR! Failed at the memoriae-api@0.0.1 test:docker script.
api_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
api_1    | 
api_1    | npm ERR! A complete log of this run can be found in:
api_1    | npm ERR!     /root/.npm/_logs/2017-12-19T17_05_26_711Z-debug.log
api_1    | [nodemon] app crashed - waiting for file changes before starting...

```

**Comment by fatiharaci** [comment]
```
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ cp src/config/environments/environments.json.example development.json
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ cp src/config/environments/environments.json.example test.json
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ cp src/config/environments/environments.json.example production.json
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ 
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ npm install
npm WARN mongoose-slug-hero@1.0.8 requires a peer of lodash@^3.10.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 116 packages in 15.044s
fatih@fatih-HP-EliteBook-745-G2:~/Desktop/574/memoriae-api$ sudo docker-compose up
[sudo] password for fatih: 
Starting memoriaeapi_mongo_1
Starting memoriaeapi_api_1
Attaching to memoriaeapi_mongo_1, memoriaeapi_api_1
mongo_1  | 2017-12-19T18:00:56.421+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=07d20ab1810b
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten] db version v3.6.0
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten] git version: a57d8e71e6998a2d0afde7edc11bd23e5661c915
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1t  3 May 2016
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten] modules: none
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten] build environment:
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten]     distmod: debian81
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1  | 2017-12-19T18:00:56.441+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
mongo_1  | 2017-12-19T18:00:56.479+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo_1  | 2017-12-19T18:00:56.479+0000 I STORAGE  [initandlisten] 
mongo_1  | 2017-12-19T18:00:56.479+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
mongo_1  | 2017-12-19T18:00:56.479+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
mongo_1  | 2017-12-19T18:00:56.622+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1215M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
mongo_1  | 2017-12-19T18:00:58.136+0000 I STORAGE  [initandlisten] WiredTiger message [1513706458:136829][1:0x7f18cb066a00], txn-recover: Main recovery loop: starting at 6/20224
mongo_1  | 2017-12-19T18:00:58.719+0000 I STORAGE  [initandlisten] WiredTiger message [1513706458:719440][1:0x7f18cb066a00], txn-recover: Recovering log 6 through 7
mongo_1  | 2017-12-19T18:00:59.114+0000 I STORAGE  [initandlisten] WiredTiger message [1513706459:114170][1:0x7f18cb066a00], txn-recover: Recovering log 7 through 7
api_1    | 
api_1    | > memoriae-api@0.0.1 docker /app
api_1    | > NODE_ENV=docker nodemon -w src -w specs --exec "npm run lint && npm run test:docker && npm start"
api_1    | 
mongo_1  | 2017-12-19T18:01:00.977+0000 I CONTROL  [initandlisten] 
mongo_1  | 2017-12-19T18:01:00.977+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo_1  | 2017-12-19T18:01:00.977+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo_1  | 2017-12-19T18:01:00.977+0000 I CONTROL  [initandlisten] 
mongo_1  | 2017-12-19T18:01:00.978+0000 I CONTROL  [initandlisten] 
mongo_1  | 2017-12-19T18:01:00.978+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
mongo_1  | 2017-12-19T18:01:00.978+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongo_1  | 2017-12-19T18:01:00.978+0000 I CONTROL  [initandlisten] 
mongo_1  | 2017-12-19T18:01:01.481+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1  | 2017-12-19T18:01:01.482+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
api_1    | [nodemon] 1.11.0
api_1    | [nodemon] to restart at any time, enter `rs`
api_1    | [nodemon] watching: /app/src/**/* /app/specs/**/*
api_1    | [nodemon] starting `npm run lint && npm run test:docker && npm start`
api_1    | 
api_1    | > memoriae-api@0.0.1 lint /app
api_1    | > eslint src
api_1    | 
api_1    | 
api_1    | > memoriae-api@0.0.1 test:docker /app
api_1    | > NODE_ENV=test_docker mocha specs --recursive
api_1    | 
api_1    | module.js:544
api_1    |     throw err;
api_1    |     ^
api_1    | 
api_1    | Error: Cannot find module './environments/development.json'
api_1    |     at Function.Module._resolveFilename (module.js:542:15)
api_1    |     at Function.Module._load (module.js:472:25)
api_1    |     at Module.require (module.js:585:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at Object.<anonymous> (/app/src/config/environment.js:3:24)
api_1    |     at Module._compile (module.js:641:30)
api_1    |     at Object.Module._extensions..js (module.js:652:10)
api_1    |     at Module.load (module.js:560:32)
api_1    |     at tryModuleLoad (module.js:503:12)
api_1    |     at Function.Module._load (module.js:495:3)
api_1    |     at Module.require (module.js:585:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at Object.<anonymous> (/app/src/index.js:8:16)
api_1    |     at Module._compile (module.js:641:30)
api_1    |     at Object.Module._extensions..js (module.js:652:10)
api_1    |     at Module.load (module.js:560:32)
api_1    |     at tryModuleLoad (module.js:503:12)
api_1    |     at Function.Module._load (module.js:495:3)
api_1    |     at Module.require (module.js:585:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at Object.<anonymous> (/app/specs/index.spec.js:3:13)
api_1    |     at Module._compile (module.js:641:30)
api_1    |     at Object.Module._extensions..js (module.js:652:10)
api_1    |     at Module.load (module.js:560:32)
api_1    |     at tryModuleLoad (module.js:503:12)
api_1    |     at Function.Module._load (module.js:495:3)
api_1    |     at Module.require (module.js:585:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at /app/node_modules/mocha/lib/mocha.js:230:27
api_1    |     at Array.forEach (<anonymous>)
api_1    |     at Mocha.loadFiles (/app/node_modules/mocha/lib/mocha.js:227:14)
api_1    |     at Mocha.run (/app/node_modules/mocha/lib/mocha.js:495:10)
api_1    |     at Object.<anonymous> (/app/node_modules/mocha/bin/_mocha:460:18)
api_1    |     at Module._compile (module.js:641:30)
api_1    |     at Object.Module._extensions..js (module.js:652:10)
api_1    |     at Module.load (module.js:560:32)
api_1    |     at tryModuleLoad (module.js:503:12)
api_1    |     at Function.Module._load (module.js:495:3)
api_1    |     at Function.Module.runMain (module.js:682:10)
api_1    |     at startup (bootstrap_node.js:191:16)
api_1    |     at bootstrap_node.js:613:3
api_1    | npm ERR! code ELIFECYCLE
api_1    | npm ERR! errno 1
api_1    | npm ERR! memoriae-api@0.0.1 test:docker: `NODE_ENV=test_docker mocha specs --recursive`
api_1    | npm ERR! Exit status 1
api_1    | npm ERR! 
api_1    | npm ERR! Failed at the memoriae-api@0.0.1 test:docker script.
api_1    | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
api_1    | 
api_1    | npm ERR! A complete log of this run can be found in:
api_1    | npm ERR!     /root/.npm/_logs/2017-12-19T18_01_10_249Z-debug.log
api_1    | [nodemon] app crashed - waiting for file changes before starting...


```

**Comment by bahattinunal** [comment]
Found the solution @fatiharaci https://www.apple.com/tr/shop/buy-mac/macbook

**Comment by bahattinunal** [comment]
@fatiharaci provide the solution you've found and we can close this issue.

**Comment by fatiharaci** [comment]
Ok FINALLY FOUND THE SOLUTION

the environment.json files are not in the correct  place; adding scripts and wiki.

```
cp src/config/environments/environments.json.example src/config/environments/development.json
cp src/config/environments/environments.json.example src/config/environments/test.json
cp src/config/environments/environments.json.example src/config/environments/production.json
```

https://github.com/574BandOfBrothers/memoriae/wiki/Auto-Deployment
